"""second

Revision ID: 11bf7e017525
Revises: 8de74b416aa8
Create Date: 2025-08-10 17:52:31.232446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11bf7e017525'
down_revision: Union[str, Sequence[str], None] = '8de74b416aa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phones', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('phones_organization_fkey'), 'phones', type_='foreignkey')
    op.create_foreign_key(None, 'phones', 'organizations', ['organization_id'], ['id'])
    op.drop_column('phones', 'organization')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phones', sa.Column('organization', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'phones', type_='foreignkey')
    op.create_foreign_key(op.f('phones_organization_fkey'), 'phones', 'organizations', ['organization'], ['id'])
    op.drop_column('phones', 'organization_id')
    # ### end Alembic commands ###
